# CPU
MAIOR_INTEIRO = 4294967296
MAIOR_REGISTRADOR = ord('D')
MENOR_REGISTRADOR = ord('A')

# MEMORIA
CLOCK_MINIMO = 100
CLOCK_MAXIMO = 1000000000
CLOCK = CLOCK_MINIMO
TAMANHO_MINIMO_MEMORIA = 32
TAMANHO_MAXIMO_MEMORIA = 32 * (2**30)
TAMANHO_MEMORIA_REAL = TAMANHO_MINIMO_MEMORIA
TAMANHO_MEMORIA_COD = TAMANHO_MEMORIA_REAL / 2
TAMANHO_MEMORIA_DADOS = TAMANHO_MEMORIA_REAL / 2
CODIGO_AREA = 16
CODIGO_SIZE = 4
OFFSET = CODIGO_AREA

# BARRAMENTO
TAMANHO_MINIMO_LARGURA_BARRAMENTO = 8
TAMANHO_MAXIMO_LARGURA_BARRAMENTO = 128
LARGURA_BARRAMENTO = 8
