# CPU
MAIOR_INTEIRO = 255
MAIOR_REGISTRADOR = ord('D')
MENOR_REGISTRADOR = ord('A')

# MEMORIA
CODIGO_SIZE = 4
MEMORIA_TAMANHO_MINIMO = 32
MEMORIA_TAMANHO_MAXIMO = 2**24
MEMORIA_TAMANHO = MEMORIA_TAMANHO_MINIMO


def memoria_particao_codigo():
    return MEMORIA_TAMANHO / 2


def memoria_particao_dados():
    return MEMORIA_TAMANHO / 2


# BARRAMENTO
CLOCK_MINIMO = 100
CLOCK_MAXIMO = 1000000000
TAMANHO_MINIMO_LARGURA_BARRAMENTO = 8
TAMANHO_MAXIMO_LARGURA_BARRAMENTO = 128

CLOCK = CLOCK_MINIMO
LARGURA_BARRAMENTO = 8


def largura_de_banda():
    return CLOCK * LARGURA_BARRAMENTO

sleep = 1

# Estrutura do vetor de conexao com os componentes

# Geral
T_LENGTH = 4
# origem, destino, dados
T_ORIGEM = 0
T_DESTINO = 1
T_DADOS = 2
T_TIPO = 3

# Instrucoes de sinal
T_L_INSTRUCAO = 0
T_L_VALOR = 1
T_E_INSTRUCAO = 2
T_E_VALOR = 3
